version: 1
project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/i-notebook.lpk
update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: i-notebook
build:
  run_buildscript: false
images:
  - id: i-notebook
    target: service
    service: i-notebook
    source: aidenzou/i-notebook
    channel: stable
    tag_regex: '^v?[0-9]+\.[0-9]+\.[0-9]+$'
    delivery:
      mode: lazycat
stores:
  official:
    enabled: true
    skip_if_version_exists: true
  private:
    enabled: true
    skip_if_version_exists: true
    name: i-notebook
    summary: 支持自部署的个人知识写作与笔记管理应用

