application:
  subdomain: i-notebook
  background_task: true
  public_path:
    - /
  routes:
    - /=http://i-notebook:3000
  injects:
    - id: unlock-code-autofill
      when:
        - /
      do:
        - src: builtin://simple-inject-password
          params:
            password: lazycat
            allowPasswordOnly: true

services:
  i-notebook:
    # upstream: aidenzou/i-notebook:0.8.0
    image: docker.1ms.run/aidenzou/i-notebook:0.8.0
    environment:
      - DATABASE_URL=file:/appdata/db/notebook.sqlite
      - AUTH_UNLOCKCODE=lazycat
    binds:
      - /lzcapp/var/data:/appdata
