application:
  subdomain: i-notebook
  background_task: true
  public_path:
    - /
  routes:
    - /=http://i-notebook:3000
  injects:
    - id: unlock-code-autofill
      when:
        - /
      do:
        - src: builtin://simple-inject-password
          params:
            password: lazycat
            allowPasswordOnly: true
services:
  i-notebook:
    # upstream: aidenzou/i-notebook:0.16.0
    image: registry.lazycat.cloud/czyt/aidenzou/i-notebook:fae10a5cc00219ea
    environment:
      - DATABASE_URL=file:/appdata/db/notebook.sqlite
      - AUTH_UNLOCKCODE=lazycat
    binds:
      - /lzcapp/var/data:/appdata
