lzc-sdk-version: "0.1"
name: i-notebook
package: cloud.lazycat.app.i-notebook
version: 0.8.0
description: 一款支持自部署的个人知识写作应用，助你更高效地组织和管理笔记。
homepage: https://hub.docker.com/r/aidenzou/i-notebook
author: aidenzou
application:
  subdomain: i-notebook
  background_task: true
  public_path:
    - /
  routes:
    - /=http://i-notebook:3000

services:
  i-notebook:
    image: docker.1ms.run/aidenzou/i-notebook:0.8.0
    environment:
      - DATABASE_URL=file:/appdata/db/notebook.sqlite
      - AUTH_UNLOCKCODE=lazycat
    binds:
      - /lzcapp/var/data:/appdata
